### PR TITLE
added 2D coordinates for keypoints

### PR DESCRIPTION
**Pull request by tobiaskalb**
To further simplify the recording of scenarios I added the 2D coordinates to the output of the csv-file as well.

### CODE REVIEW

**Comment by fabbrimatteo** [comment]
Thank you @KuehlschrankDino.

Can you also provide the new DatasetAnnotator.asi file compiled using the branch you are merging?

So that I can add it to the README.

**Comment by tobiaskalb** [comment]
Here you go: [DatasetAnnotator.asi](https://drive.google.com/file/d/19MigtxxsME9ske24WacZTuXcSBY73xlx/view?usp=sharing)
Thank you, for providing this Mod Open Source!

**Comment by fabbrimatteo** [comment]
Hey @KuehlschrankDino, 

Thank you again for the contribution. Can you please also provide the ScenarioCreator.asi (if you compiled it with the latest ScriptHook version)? I think that my asi files are outdated.

**Comment by tobiaskalb** [comment]
Well I didn't compile it with the latest ScriptHook Version version, but I surely used a different version. 
On another note I noticed that I put the 2D Coordinates in a different order than on the orignal JTA-Dataset which is annoying. Is it ok if I open another pull request for that? I would provide the new .asi files as well.

**Comment by fabbrimatteo** [comment]
Sorry for the delay. Yes, go for the pull request!

When you submit the pull request, can you provide both .asi files?

**Pull request merged**
